export const OPENWEATHERMAP_BASE_URL = process.env.NEXT_PUBLIC_OPENWEATHERMAP_BASE_URL;
export const OPENWEATHERMAP_API_KEY = process.env.NEXT_PUBLIC_OPENWEATHERMAP_API_KEY;
export const DEFAULT_CITY_ID = process.env.NEXT_PUBLIC_DEFAULT_CITY_ID || 3686540; // Chinú, CO
